// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoOIKyDaBJOmDLGCwNIQpEQDJqmw46vxA',
    appId: '1:224939592324:web:cde9bd3791edaf302fd0d1',
    messagingSenderId: '224939592324',
    projectId: 'mobilepraktikum-479f2',
    authDomain: 'mobilepraktikum-479f2.firebaseapp.com',
    storageBucket: 'mobilepraktikum-479f2.appspot.com',
    measurementId: 'G-LWH5P0Z3GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHDjZtZTnz9aqAlvCanYOencJ3SGSzCFQ',
    appId: '1:224939592324:android:7518e7c57e1b2ced2fd0d1',
    messagingSenderId: '224939592324',
    projectId: 'mobilepraktikum-479f2',
    storageBucket: 'mobilepraktikum-479f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXy6hL9hVmvLABuehPaw9Kv3zpLbiX_GQ',
    appId: '1:224939592324:ios:07a249c7088c22582fd0d1',
    messagingSenderId: '224939592324',
    projectId: 'mobilepraktikum-479f2',
    storageBucket: 'mobilepraktikum-479f2.appspot.com',
    iosBundleId: 'com.example.myapp',
  );
}
